version: '3.9'

services:
  mongodb:
    image: mongo
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db

  redis:
      image: redis
      container_name: redis
      command: redis-server --requirepass ${REDIS_PASSWORD}
      ports: 
          - "6379:6379"
      networks: 
          - main
      restart: on-failure
      volumes:
          - redisdata:/data

  app:
      build: .
      container_name: app
      restart: on-failure
      command: sh -c "alembic revision --autogenerate -m 'first commit' &&
                      alembic upgrade head &&
                      uvicorn config.main:app --reload --host 0.0.0.0 "
      depends_on: 
          - mongodb
      expose: 
          - "8000"
      networks:
          - main
      volumes: 
          - .:/code/

  nginx:
      image: nginx
      container_name: nginx
      command: nginx -g 'daemon off;'
      restart: on-failure
      depends_on:
          - app
      networks: 
          - main
      ports: 
          - "80:80"
      volumes: 
          - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        

        
networks: 
    main:  
        external: false

volumes:
  mongo:
    external: false

  redisdata:
      external: false
