version: '3.9'

services:
  mongodb:
    image: mongo
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db

  redis:
      image: redis
      container_name: redis
      command: redis-server --requirepass ${REDIS_PASSWORD}
      ports: 
          - "6379:6379"
      networks: 
          - main
      restart: on-failure
      volumes:
          - redisdata:/data


networks: 
    main:  
        external: false

volumes:
  mongo:
    external: false

  redisdata:
      external: false